import React,{useEffect,useMemo,useState} from 'react';
import {Activity, BriefcaseBusiness, Building2, CheckCircle2, ClipboardList, FileText, RefreshCw, Search, ShieldCheck, Trash2, Users, X} from 'lucide-react';
import {apiRequest} from '../../utils/api';
import toast from 'react-hot-toast';
import SearchableSelect from '../common/SearchableSelect';

const blank={name:'',email:'',password:'',role:'team_member'};
const input='w-full p-2.5 rounded-lg bg-slate-800/80 border border-white/10 placeholder-white/35 focus:outline-none focus:border-emerald-400/60 focus:ring-2 focus:ring-emerald-400/10 transition';
const statConfig=[
  ['Users', 'users', Users, 'from-blue-500/25 to-cyan-500/10'],
  ['Clients', 'clients', Building2, 'from-violet-500/25 to-blue-500/10'],
  ['Services', 'services', BriefcaseBusiness, 'from-emerald-500/25 to-teal-500/10'],
  ['Engagements', 'engagements', ClipboardList, 'from-amber-500/25 to-orange-500/10'],
  ['Tasks', 'tasks', CheckCircle2, 'from-sky-500/25 to-blue-500/10'],
  ['Audits', 'logs', Activity, 'from-rose-500/25 to-pink-500/10'],
];

export default function AdminDashboardEnhanced({onBackToHome,onNavigateToProfile}){
 const [data,setData]=useState({users:[],clients:[],services:[],engagements:[],tasks:[],logs:[]});
 const [recordSearch,setRecordSearch]=useState('');
 const managerUsers = data.users.filter(u => String(u.role || '').trim().toLowerCase() === 'manager' && u.isActive !== false);
 const teamMemberUsers = data.users.filter(u => String(u.role || '').trim().toLowerCase() === 'team_member' && u.isActive !== false);
 const [user,setUser]=useState(blank),[client,setClient]=useState({name:'',email:'',phone:'',address:''}),[service,setService]=useState({name:'',description:'',engagementType:'one_time',recurrence:'monthly'}),[template,setTemplate]=useState({serviceTypeId:'',title:'',description:'',defaultDueDays:7,order:0}),[eng,setEng]=useState({clientId:'',serviceTypeId:'',managerId:'',title:'',period:'',startDate:''}),[task,setTask]=useState({engagementId:'',title:'',description:'',assignedTo:'',dueDate:''});
 const load=async()=>{const [users,clients,services,engagements,tasks,logs]=await Promise.all([apiRequest('/users'),apiRequest('/clients'),apiRequest('/services'),apiRequest('/engagements'),apiRequest('/tasks'),apiRequest('/audit-logs')]);setData({users,clients,services,engagements,tasks,logs})};
 useEffect(()=>{load().catch(e=>toast.error(e.message))},[]);
 const post=async(path,body,reset)=>{try{await apiRequest(path,{method:'POST',body:JSON.stringify(body)});reset();await load();toast.success('Saved successfully')}catch(e){toast.error(e.message)}};
 const del=async(path,label)=>{if(!confirm(`Delete ${label || 'this record'}? This action cannot be undone.`))return;try{await apiRequest(path,{method:'DELETE'});await load();toast.success('Deleted successfully')}catch(e){toast.error(e.message)}};
 const filteredRecords=useMemo(()=>{const q=recordSearch.trim().toLowerCase();const match=x=>!q||[x.name,x.title,x.email,x.period,x.status].some(v=>String(v||'').toLowerCase().includes(q));return {users:data.users.filter(match),clients:data.clients.filter(match),services:data.services.filter(match),engagements:data.engagements.filter(match),tasks:data.tasks.filter(match)}},[data,recordSearch]);
 const recordGroups=[['users','Users','/users',filteredRecords.users],['clients','Clients','/clients',filteredRecords.clients],['services','Services','/services',filteredRecords.services],['engagements','Engagements','/engagements',filteredRecords.engagements],['tasks','Tasks','/tasks',filteredRecords.tasks]];
 return <div className="admin-theme min-h-screen text-white p-4 md:p-6 lg:p-8">
  <header className="admin-header flex flex-wrap justify-between gap-4 mb-7">
   <div className="flex items-start gap-3"><div className="admin-brand-icon"><ShieldCheck className="w-6 h-6"/></div><div><h1 className="text-3xl md:text-4xl font-bold tracking-tight">Admin Control Center</h1><p className="text-white/55 mt-1">Manage users, clients, services, engagements and workflow activity.</p></div></div>
   <div className="flex gap-2 items-center"><button className="admin-action admin-action-primary" onClick={()=>load()}><RefreshCw className="w-4 h-4"/>Refresh</button><button className="admin-action" onClick={onNavigateToProfile}>Profile</button><button className="admin-action admin-action-danger" onClick={onBackToHome}>Logout</button></div>
  </header>

  <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-3 mb-7">{statConfig.map(([label,key,Icon,gradient])=><div key={key} className={`admin-stat bg-gradient-to-br ${gradient}`}><div className="flex items-center justify-between"><span className="text-white/60 text-sm">{label}</span><Icon className="w-4 h-4 text-white/50"/></div><b className="text-3xl mt-2 block">{data[key].length}</b></div>)}</div>

  <div className="grid lg:grid-cols-3 gap-5">
   <section className="admin-panel"><div className="admin-section-title"><div><h2>Create user</h2><p>Add a manager or team member to the workspace.</p></div><Users className="text-cyan-300"/></div><form onSubmit={e=>{e.preventDefault();post('/users',user,()=>setUser(blank))}}>{['name','email','password'].map(k=><input className={input+' my-1.5'} required key={k} placeholder={k} type={k==='password'?'password':'text'} value={user[k]} onChange={e=>setUser({...user,[k]:e.target.value})}/>)}<select className={input+' my-1.5'} value={user.role} onChange={e=>setUser({...user,role:e.target.value})}><option value="team_member">Team Member</option><option value="manager">Manager</option><option value="admin">Admin</option></select><button className="admin-btn">Create user</button></form></section>
   <section className="admin-panel"><div className="admin-section-title"><div><h2>Create client</h2><p>Keep client contact information available to the team.</p></div><Building2 className="text-violet-300"/></div><form onSubmit={e=>{e.preventDefault();post('/clients',client,()=>setClient({name:'',email:'',phone:'',address:''}))}}>{Object.keys(client).map(k=><input className={input+' my-1.5'} required={k==='name'} key={k} placeholder={k} value={client[k]} onChange={e=>setClient({...client,[k]:e.target.value})}/>)}<button className="admin-btn">Create client</button></form></section>
   <section className="admin-panel"><div className="admin-section-title"><div><h2>Create service</h2><p>Define one-time or recurring service workflows.</p></div><BriefcaseBusiness className="text-emerald-300"/></div><form onSubmit={e=>{e.preventDefault();post('/services',service,()=>setService({name:'',description:'',engagementType:'one_time',recurrence:'monthly'}))}}><input className={input+' my-1.5'} required placeholder="name" value={service.name} onChange={e=>setService({...service,name:e.target.value})}/><input className={input+' my-1.5'} placeholder="description" value={service.description} onChange={e=>setService({...service,description:e.target.value})}/><select className={input+' my-1.5'} value={service.engagementType} onChange={e=>setService({...service,engagementType:e.target.value})}><option value="one_time">One-time</option><option value="recurring">Recurring</option></select><select className={input+' my-1.5'} value={service.recurrence} onChange={e=>setService({...service,recurrence:e.target.value})}><option>monthly</option><option>quarterly</option><option>yearly</option></select><button className="admin-btn">Create service</button></form></section>
   <section className="admin-panel"><div className="admin-section-title"><div><h2>Create template</h2><p>Configure task templates for a service.</p></div><FileText className="text-amber-300"/></div><form onSubmit={e=>{e.preventDefault();if(!template.serviceTypeId){toast.error('Please select a service');return;}post('/services/'+template.serviceTypeId+'/templates',template,()=>setTemplate({serviceTypeId:'',title:'',description:'',defaultDueDays:7,order:0}))}}><SearchableSelect required value={template.serviceTypeId} onChange={value=>setTemplate({...template,serviceTypeId:value})} options={data.services.map(s=>({value:s._id,label:s.name,secondary:s.description}))} placeholder="Select service" searchPlaceholder="Search services..." className="my-1.5" />{['title','description','defaultDueDays','order'].map(k=><input className={input+' my-1.5'} required={k==='title'} key={k} placeholder={k} type={k==='defaultDueDays'||k==='order'?'number':'text'} value={template[k]} onChange={e=>setTemplate({...template,[k]:e.target.value})}/>)}<button className="admin-btn">Create template</button></form></section>
   <section className="admin-panel"><div className="admin-section-title"><div><h2>Create engagement</h2><p>Assign an engagement to an active manager.</p></div><ClipboardList className="text-cyan-300"/></div><form onSubmit={e=>{e.preventDefault();if(!eng.clientId||!eng.serviceTypeId||!eng.managerId){toast.error('Please select client, service and manager');return;}post('/engagements',eng,()=>setEng({clientId:'',serviceTypeId:'',managerId:'',title:'',period:'',startDate:''}))}}><SearchableSelect required value={eng.clientId} onChange={value=>setEng({...eng,clientId:value})} options={data.clients.map(x=>({value:x._id,label:x.name||x.email,secondary:x.email}))} placeholder="Select client" searchPlaceholder="Search clients..." className="my-1.5" /><SearchableSelect required value={eng.serviceTypeId} onChange={value=>setEng({...eng,serviceTypeId:value})} options={data.services.map(x=>({value:x._id,label:x.name,secondary:x.description}))} placeholder="Select service" searchPlaceholder="Search services..." className="my-1.5" /><SearchableSelect required value={eng.managerId} onChange={value=>setEng({...eng,managerId:value})} options={managerUsers.map(x=>({value:x._id,label:x.name||x.email,secondary:x.email}))} placeholder="Select Manager" searchPlaceholder="Search managers..." className="my-1.5" />{['title','period','startDate'].map(k=><input required className={input+' my-1.5'} key={k} placeholder={k} type={k==='startDate'?'date':'text'} value={eng[k]} onChange={e=>setEng({...eng,[k]:e.target.value})}/>)}<button className="admin-btn">Create engagement</button></form></section>
   <section className="admin-panel"><div className="admin-section-title"><div><h2>Create task</h2><p>Create a task under an existing engagement.</p></div><CheckCircle2 className="text-blue-300"/></div><form onSubmit={e=>{e.preventDefault();if(!task.engagementId){toast.error('Please select an engagement');return;}post('/tasks',task,()=>setTask({engagementId:'',title:'',description:'',assignedTo:'',dueDate:''}))}}><SearchableSelect required value={task.engagementId} onChange={value=>setTask({...task,engagementId:value})} options={data.engagements.map(x=>({value:x._id,label:x.title,secondary:`${x.clientId?.name||'Client'} · ${x.period||''}`}))} placeholder="Select engagement" searchPlaceholder="Search engagements..." className="my-1.5" />{['title','description','dueDate'].map(k=><input required={k!=='description'} className={input+' my-1.5'} key={k} placeholder={k} type={k==='dueDate'?'date':'text'} value={task[k]} onChange={e=>setTask({...task,[k]:e.target.value})}/>)}<SearchableSelect value={task.assignedTo} onChange={value=>setTask({...task,assignedTo:value})} options={teamMemberUsers.map(u=>({value:u._id,label:u.name||u.email,secondary:u.email}))} placeholder="Unassigned" searchPlaceholder="Search team members..." className="my-1.5" /><button className="admin-btn">Create task</button></form></section>
  </div>

  <div className="grid xl:grid-cols-5 gap-5 mt-5">
   <section className="admin-panel xl:col-span-3 min-w-0"><div className="admin-section-title"><div><h2>Records</h2><p>Search and manage application records.</p></div><div className="relative w-56 max-w-full"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-white/35"/><input value={recordSearch} onChange={e=>setRecordSearch(e.target.value)} placeholder="Search records..." className="w-full pl-9 pr-8 py-2 rounded-lg bg-white/5 border border-white/10 text-sm focus:outline-none focus:border-emerald-400/50"/>{recordSearch&&<X className="absolute right-2 top-1/2 -translate-y-1/2 w-4 h-4 text-white/35 cursor-pointer" onClick={()=>setRecordSearch('')}/>}</div></div><div className="admin-records-scroll">{recordGroups.map(([key,label,path,items])=><div key={key} className="mb-5 last:mb-0"><div className="flex items-center justify-between mb-2"><h3 className="text-cyan-300 font-semibold">{label}</h3><span className="text-xs text-white/35">{items.length}</span></div>{items.map(x=><div className="admin-record-row" key={x._id}><div className="min-w-0"><span className="block truncate">{x.name||x.title||x.email||x._id}</span>{(x.email||x.period||x.status)&&<span className="block text-xs text-white/35 truncate">{x.email||x.period||x.status}</span>}</div>{<button className="admin-delete" onClick={()=>del(path+'/'+x._id,`${label.slice(0,-1)} record`)}><Trash2 className="w-3.5 h-3.5"/>Delete</button>}</div>)}{!items.length&&<p className="text-xs text-white/35 py-2">No records found.</p>}</div>)}</div></section>
   <section className="admin-panel xl:col-span-2 min-w-0"><div className="admin-section-title"><div><h2>Audit log</h2><p>Activity history is retained for traceability.</p></div><Activity className="text-rose-300"/></div><div className="admin-audit-scroll">{data.logs.map(l=><div className="admin-audit-row" key={l._id}><div className="flex items-start justify-between gap-3"><div><b className="text-emerald-300">{l.action}</b> <span>{l.entity}</span><div className="text-xs text-white/45 mt-1">{l.actor?.email||'system'}</div></div><span className="text-xs text-white/35 whitespace-nowrap">{new Date(l.createdAt).toLocaleString()}</span></div></div>)}{!data.logs.length&&<p className="text-sm text-white/40 py-4">No audit activity yet.</p>}</div></section>
  </div>
 </div>
}
